version: '2'

services:

  ubuntutouch-build:
    build:
      context: 15.04
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    privileged: true

  ubuntutouch:
    image: timbaler/cordova-ubuntutouch:15.04
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    privileged: true
    volumes:
      - ./myapp:/app


  android-build:
    build:
      context: android23

  android:
    image: timbaler/cordova-ubuntutouch:android23
    volumes:
      - ./myapp:/app
